### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by Darlenequame** [rezwanulhaquerezwan/Online-Voting-System-using-php-and-mysql#1]
Fatal error: Uncaught Error: Call to undefined function mysql_error() in C:\xampp\htdocs\online_voting\connection.php:4 Stack trace: #0 C:\xampp\htdocs\online_voting\admin\checklogin.php(13): require() #1 {main} thrown in C:\xampp\htdocs\online_voting\connection.php on line 4

**Comment by Darlenequame** [comment]
got it working..... am new to github but willing to contribute to this project how to I help?

**Comment by deepthi2514** [comment]
> Fatal error: Uncaught Error: Call to undefined function mysql_error() in C:\xampp\htdocs\online_voting\connection.php:4 Stack trace: #0 C:\xampp\htdocs\online_voting\admin\checklogin.php(13): require() #1 {main} thrown in C:\xampp\htdocs\online_voting\connection.php on line 4
> 
> facing deprecated SQL codes

im also facing same issue pls tell us which version we need to use to clear that error please sir its very needed

**Comment by Darlenequame** [comment]
Please use mysqli mysql is deprecated

Darlington Adusei

**Comment by deepthi2514** [comment]
should we change it in whole code

**Comment by deepthi2514** [comment]
i have used but its showing blue screen plz sir help to make this code run

**Comment by Darlenequame** [comment]
Please change all instances using mysql to mysqli

Darlington Adusei
